sudo: true
dist: trusty
language: sh
addons:
  apt:
    packages:
      - build-essential

services:
  - docker

before_script:
  # Show the git version being used to test.
  - "git --version"
  # Show the zsh version being used to test.
  - "zsh --version"

before_install:
  - docker build -t powerlevel9k ./test
  - docker run -d powerlevel9k /bin/zsh -c "cd /root/powerlevel9k"
  - docker ps -a
  - docker run powerlevel9k /bin/zsh -c "cd /root/powerlevel9k; ./test/executeTests.sh"

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install zsh"
  - "sudo chsh -s $(which zsh)"

script:
  - test/powerlevel9k.spec
  - test/functions/utilities.spec
  - test/functions/colors.spec
  - test/segments/dir.spec
  - test/segments/rust_version.spec
  - test/segments/go_version.spec
  - test/segments/vcs.spec

